### ISSUE TITLE
Dead project? Future plans and architecture

### ISSUE THREAD

**Issue by snugghash** [timqian/comment-chain#1]
Greetings,
I find the need exists for a comment-on-every-webpage thing. Frankly I'm surprised it doesn't exist yet, it's pretty valuable, especially for fake news and all sorts of random internet comraderie. 

What was the planned architecture for this? Injected disqus via greasemonkey or another browser extension like I was envisioning perhaps? If you have any thoughts, use cases, something that would make this extremely valuable, some distribution strategy to get this viral - I'd appreciate them all.

Thanks

**Comment by timqian** [comment]
You can find several existed projects like:
- https://chrome.google.com/webstore/detail/common-%C2%B7-comment-on-any-w/pdjjlgfdgbbppcjioaijkeahioaocoep
- https://chrome.google.com/webstore/detail/review-and-comment-on-any/knlnhookpeoheicigpcefcajopekmmli
- https://urlchatbox.com/#step-1
- https://chrome.google.com/webstore/detail/find-people-on-the-same-w/bldcellajihanglphncgjmceklbibjkk

And even google has done something similar before
- https://en.wikipedia.org/wiki/Google_Sidewiki
- https://www.pcworld.com/article/172544/The_Good_and_Bad_of_Google_Sidewiki.html
- https://www.quora.com/What-services-are-similar-to-Google-Sidewiki

This idea sounds good, but I haven't think much about it. How to make it really useful instead of becoming another failed project or finding very small amount of users as listed above

**Comment by snugghash** [comment]
Thanks for your work so far. I'll remember this issue and you as a good sounding board when brainstorming distribution strategies. Google has always been shit at distribution strategy and marketing - that's no indicator. There's a need for this, I believe I can find ways to make this ubiquitous.

**Comment by timqian** [comment]
@snugghash Good luck, I will be glad to follow your progress.
